[project]
name = 'Blockchain-Based-Hotel-Group-Sales-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.commission-management]
path = 'contracts/commission-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.corporate-client]
path = 'contracts/corporate-client.clar'
clarity_version = 2
epoch = 2.5

[contracts.property-verification]
path = 'contracts/property-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.room-allocation]
path = 'contracts/room-allocation.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
